services:
  helix-configurator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./helix-otel-collector.yaml:/app/helix-otel-collector.yaml
      - ./.env:/app/.env
    environment:
      - HELIX_ENDPOINT=${HELIX_ENDPOINT}
      - HELIX_API_KEY=${HELIX_API_KEY}
      - X_SOURCE=${X_SOURCE}
      - TARGET_CONTAINER_NAME=${TARGET_CONTAINER_NAME}
