// AIOps mock endpoint (public) — simulates the BMC Helix AIOps "Manage
// Opentelemetry" wizard: takes the X-Source name, fabricates an API key
// that looks like a real Helix one, and streams back a zip of everything
// needed to run the HelixConfigurator sidecar on Mac/Linux/Windows. The
// ingest endpoint is an obvious placeholder so the bundle doesn't leak
// whichever tenant the demo host happens to point at — the user fills in
// their real endpoint at Step 1 of the wizard. (In a real AIOps
// integration, the tenant URL would be known and substituted here.)
//
// Per TODO #7 — every route here lives under /api/_demo/aiops/* so the
// demo/product boundary is visible in URLs. A future env flag can gate
// the whole module behind IS_DEMO_INSTALL=true.
const crypto = require('crypto');
const path = require('path');
const archiver = require('archiver');
const { marked } = require('marked');
const { computeInstallBaseUrl } = require('../util');

const SIMULATED_INGEST_ENDPOINT = 'https://your-tenant.onbmc.com';

const fakeHelixApiKey = () => `FAKE-KEY-${crypto.randomBytes(16).toString('hex').toUpperCase()}`;

const renderCollectorYaml = ({ endpoint, apiKey, xSource }) => `receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
exporters:
  otlphttp/bmchelix:
    endpoint: \${env:HELIX_ENDPOINT}
    headers:
      X-Api-Key: \${env:HELIX_API_KEY}
      X-Source: \${env:X_SOURCE}
    # Sending queue tuned for sustained burst throughput to Helix.
    # num_consumers = parallel HTTP workers shipping batches; queue_size is
    # bounded so the collector won't OOM under prolonged backpressure.
    sending_queue:
      enabled: true
      num_consumers: 100
      queue_size: 10000
  # Fan-out: traces and logs also flow to the configurator backend so the
  # local "View OTel Data" page can render waterfalls, errors, and DB insight.
  otlphttp/helix_local_viewer:
    traces_endpoint: http://helix-configurator:3001/api/otlp/traces
    logs_endpoint: http://helix-configurator:3001/api/otlp/logs
    encoding: json
    compression: none
    tls:
      insecure: true
    sending_queue:
      enabled: false
    retry_on_failure:
      enabled: false
service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/bmchelix, otlphttp/helix_local_viewer]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/bmchelix]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/bmchelix, otlphttp/helix_local_viewer]
`;

const renderEnvFile = ({ endpoint, apiKey, xSource }) => {
  // Defensive: this function MUST only emit values from the AIOps session
  // ctx (xSource from the form, fake apiKey, simulated endpoint). It must
  // never include host-side secrets like UI_AUTH_PASSWORD or a real
  // HELIX_API_KEY pulled from process.env. The body below already follows
  // that rule; the asserts after it catch any future regression at
  // bundle-time so a leaky build can't ship.
  const out = `# Generated by the SIMULATED BMC Helix AIOps "Manage Opentelemetry" page.
# NOTE: HELIX_API_KEY below is a fake, locally-generated key — it will not
# authenticate against a real Helix tenant. Replace it before going to prod.
# Source: ${xSource}
HELIX_ENDPOINT=${endpoint}
HELIX_API_KEY=${apiKey}
X_SOURCE=${xSource}
APP_URL=
BUSINESS_SERVICE_KEY=
`;

  const hostPassword = process.env.UI_AUTH_PASSWORD;
  if (hostPassword && out.includes(hostPassword)) {
    throw new Error('renderEnvFile: refusing to ship — host UI_AUTH_PASSWORD leaked into bundle');
  }
  const hostApiKey = process.env.HELIX_API_KEY;
  if (hostApiKey && !String(apiKey).startsWith('FAKE-KEY-') && out.includes(hostApiKey)) {
    throw new Error('renderEnvFile: refusing to ship — host HELIX_API_KEY leaked into bundle');
  }
  if (/UI_AUTH_PASSWORD/i.test(out)) {
    throw new Error('renderEnvFile: refusing to ship — UI_AUTH_PASSWORD must never appear in the install bundle');
  }
  return out;
};

const renderDockerCompose = () => `services:
  helix-configurator:
    build:
      context: .
      dockerfile: Dockerfile
    image: helix-configurator:local
    # Stable hostname so the gateway can fan trace data out to
    # http://helix-configurator:3001 over the helix-bridge network.
    container_name: helix-configurator
    ports:
      # 8765 chosen over 3000 because it almost never collides with common
      # dev tools (Node, Vite, Django, etc. cluster around 3000/5000/8000).
      - "8765:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./helix-otel-collector.yaml:/app/helix-otel-collector.yaml
      - ./.env:/app/.env
      # Persist the local OTel trace store across container restarts.
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TARGET_CONTAINER_NAME=helix-gateway
    depends_on:
      - helix-gateway
    networks:
      - helix-bridge

  helix-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: helix-gateway
    ports:
      - '4317:4317'
      - '4318:4318'
      - '8888:8888'
    env_file:
      - .env
    volumes:
      - ./helix-otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - helix-bridge

networks:
  helix-bridge:
    name: helix-bridge
    driver: bridge
`;

// Shared shell-script body used by both start.sh (Linux/headless) and
// start.command (Mac double-click — Finder runs .command in Terminal).
// `interactive` adds a "press Return to close" pause so a Finder-launched
// Terminal window doesn't vanish on error or success.
const renderShellLauncher = ({ interactive }) => `#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"
echo "================================================"
echo " Helix OTel Configurator Sidecar"
echo "================================================"
echo ""
if ! command -v docker >/dev/null 2>&1; then
  echo "Docker isn't installed. Install Docker Desktop and re-run:"
  echo "  https://www.docker.com/products/docker-desktop/"
${interactive ? '  read -p "Press Return to close..." _\n' : ''}  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "Docker is installed but not running. Open Docker Desktop and try again."
${interactive ? '  read -p "Press Return to close..." _\n' : ''}  exit 1
fi
echo "Starting (first run builds the image — this can take a few minutes)..."
docker compose up -d --build
echo ""
echo "Waiting for the configurator UI to come online..."
deadline=$(( $(date +%s) + 60 ))
while [ $(date +%s) -lt $deadline ]; do
  if curl -fsS http://localhost:8765/api/health >/dev/null 2>&1; then
    echo "Opening README and configurator UI..."
    if [ "$(uname)" = "Darwin" ]; then
      [ -f README.html ] && open README.html || true
      open "http://localhost:8765?view=onboarding" || true
    elif [ -n "$DISPLAY" ] && command -v xdg-open >/dev/null 2>&1; then
      [ -f README.html ] && (xdg-open README.html >/dev/null 2>&1 &)
      (xdg-open "http://localhost:8765?view=onboarding" >/dev/null 2>&1 &)
    fi
    break
  fi
  sleep 1
done
echo ""
echo "Sidecar is up."
echo "  Configurator UI:  http://localhost:8765"
echo "  OTLP gRPC:        localhost:4317"
echo "  OTLP HTTP:        localhost:4318"
echo ""
echo "Stop with: docker compose down"
${interactive ? 'echo ""\nread -p "Press Return to close this window..." _\n' : ''}`;

const renderStartBat = () => `@echo off
setlocal
cd /d "%~dp0"
echo ================================================
echo  Helix OTel Configurator Sidecar
echo ================================================
echo.
where docker >nul 2>&1
if errorlevel 1 (
  echo Docker isn't installed. Install Docker Desktop and re-run:
  echo   https://www.docker.com/products/docker-desktop/
  echo.
  pause
  exit /b 1
)
docker info >nul 2>&1
if errorlevel 1 (
  echo Docker is installed but not running. Open Docker Desktop and try again.
  echo.
  pause
  exit /b 1
)
echo Starting ^(first run builds the image -- this can take a few minutes^)...
docker compose up -d --build
if errorlevel 1 (
  echo.
  echo Failed to start. See errors above.
  pause
  exit /b 1
)
echo.
echo Waiting for the configurator UI to come online...
set /a "_waited=0"
:waitloop
powershell -NoProfile -Command "try { Invoke-WebRequest -UseBasicParsing -Uri 'http://localhost:8765/api/health' -TimeoutSec 2 | Out-Null; exit 0 } catch { exit 1 }" >nul 2>&1
if not errorlevel 1 (
  echo Opening README and configurator UI...
  if exist "%~dp0README.html" start "" "%~dp0README.html"
  start "" "http://localhost:8765?view=onboarding"
  goto :ready
)
set /a "_waited+=1"
if %_waited% geq 60 goto :ready
timeout /t 1 /nobreak >nul
goto :waitloop
:ready
echo.
echo Sidecar is up.
echo   Configurator UI:  http://localhost:8765
echo   OTLP gRPC:        localhost:4317
echo   OTLP HTTP:        localhost:4318
echo.
echo Stop with: docker compose down
echo.
pause
`;

const renderReadme = ({ xSource, endpoint }) => `# Helix OTel Configurator Sidecar

Generated by the **simulated** BMC Helix AIOps page for source **${xSource}**.

> ⚠️ The \`HELIX_API_KEY\` in \`.env\` is a fake key produced by the demo
> backend — it will not authenticate against a real Helix tenant. Replace it
> with a real key from your tenant before sending production telemetry.

This package runs the Helix OTel Configurator alongside an OpenTelemetry
collector that forwards traces/metrics/logs to:

    ${endpoint}

## Prerequisites

- Docker Desktop (Mac / Windows) or Docker Engine + Compose plugin (Linux)
- ~3 GB free disk for the first build (Node base images + dependencies)

## Run

### Mac (one click)
**Double-click \`start.command\`** in Finder. A Terminal window opens, builds
the image on first run, and starts the sidecar.

> First time only: macOS Gatekeeper may warn that the file was downloaded
> from the internet. Right-click \`start.command\` → **Open** → **Open**, and
> macOS will remember the choice for next time.

### Windows (one click)
**Double-click \`start.bat\`** in Explorer. A console window opens, builds
the image on first run, and starts the sidecar.

### Linux (terminal)
\`\`\`bash
chmod +x start.sh
./start.sh
\`\`\`

The first run builds the configurator image locally (no registry pull
required) and may take a few minutes. Subsequent runs reuse the cached image
and start in seconds.

## Update

To pick up new releases of the configurator, run the update script that
ships in this bundle:

| Platform | Command |
| --- | --- |
| Mac | Double-click \`update.command\` (or run \`./update.sh\` in Terminal) |
| Linux | \`./update.sh\` |
| Windows | Double-click \`update.bat\` |

The update script preserves your user-owned files while refreshing the
source code:

- \`.env\` — your credentials and source name
- \`helix-otel-collector.yaml\` — gateway pipeline config (including any edits
  you made via the dashboard YAML editor)
- \`data/\` — local OTel trace store database

Everything else (\`Dockerfile\`, \`docker-compose.yml\`, \`backend/\`,
\`frontend/\`, \`start.*\`, \`update.*\`, this README) is replaced with the
fresh bundle content, and \`docker compose up -d --build\` rebuilds the
image with the updated source.

If extraction fails mid-update, the script restores the preserved files
into a fresh \`helix-configurator/\` so you're never left without your
\`.env\`.

> **What if the update script fails to download?** The install host's URL
> is baked into \`update.*\` at the time of generation; if that tunnel URL
> has changed since your install, re-open the simulated AIOps page in your
> tenant, re-enter your source name (\`${xSource}\`), and copy the new
> \`curl ... | sh\` / \`iwr ... | iex\` command. Running that command is
> functionally equivalent to running \`./update.sh\` and bakes the new URL
> into the next bundle.

## What's inside

| File | Purpose |
| --- | --- |
| \`docker-compose.yml\` | Brings up the configurator + OTel collector |
| \`Dockerfile\` | Build instructions for the configurator image |
| \`backend/\`, \`frontend/\`, \`templates/\` | Configurator source (used at build time) |
| \`helix-otel-collector.yaml\` | Collector pipeline config |
| \`.env\` | Your generated credentials and source name (hidden — \`ls -a\` to see) |
| \`start.command\` | Mac double-click launcher |
| \`start.bat\` | Windows double-click launcher |
| \`start.sh\` | Linux / terminal launcher |
| \`update.command\` / \`update.sh\` / \`update.bat\` | Refresh source from the install host, preserve \`.env\` / \`data/\` |

> **Where's \`.env\`?** It's a dotfile, so \`ls\` won't show it on macOS / Linux.
> Run \`ls -a\` to confirm it's there. The Finder hides it by default; press
> ⌘⇧. (cmd-shift-period) to reveal hidden files.

## Endpoints

- Configurator UI: http://localhost:8765
- OTLP gRPC ingest: localhost:4317
- OTLP HTTP ingest: localhost:4318
- Collector internal metrics: http://localhost:8888/metrics

Point your instrumented application at \`http://localhost:4317\` (gRPC) or
\`http://localhost:4318\` (HTTP) and the collector will forward to Helix.

## Stop

\`\`\`bash
docker compose down
\`\`\`
`;

// In-memory session store for the AIOps configure → install → download flow.
// A session pins the apiKey + xSource so the value shown in the UI matches
// what's in the downloaded zip / installed .env. TTL is 1h; cleaned every 10m.
const aiopsSessions = new Map();
const AIOPS_SESSION_TTL_MS = 60 * 60 * 1000;
setInterval(() => {
  const now = Date.now();
  for (const [tok, s] of aiopsSessions.entries()) {
    if (now - s.createdAt > AIOPS_SESSION_TTL_MS) aiopsSessions.delete(tok);
  }
}, 10 * 60 * 1000).unref();

// HTML wrapper for the rendered README — a self-contained file we ship in
// the install bundle so start.{bat,sh,command} can open it in the user's
// default browser without depending on any .md file association.
const renderReadmeHtml = (ctx) => {
  const body = marked.parse(renderReadme(ctx));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Helix OTel Configurator — getting started</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    max-width: 760px;
    margin: 0 auto;
    padding: 32px 24px 64px;
    color: #1f2330;
    background: #fafbfc;
  }
  @media (prefers-color-scheme: dark) {
    body { color: #e6e8ee; background: #1b1f29; }
    code { background: #2a3140; }
    pre { background: #11151c; }
    a { color: #8ca1f3; }
    table th { background: #2a3140; }
    table td, table th { border-color: #2a3140; }
    blockquote { border-left-color: #4040d9; color: #d5d6dd; }
  }
  h1 { font-size: 1.875rem; margin: 0 0 0.5em; }
  h2 { margin-top: 2em; border-bottom: 1px solid #d5d6dd; padding-bottom: 0.25em; }
  h3 { margin-top: 1.5em; }
  code { font: 0.9em "SF Mono", "Source Code Pro", Menlo, Consolas, monospace; background: #eef0f5; padding: 1px 6px; border-radius: 3px; }
  pre { background: #f1f1f4; padding: 12px 14px; border-radius: 6px; overflow-x: auto; }
  pre code { background: transparent; padding: 0; }
  blockquote { border-left: 4px solid #4040d9; margin: 1em 0; padding: 0.25em 1em; color: #555; background: rgba(64,64,217,0.06); }
  table { border-collapse: collapse; width: 100%; }
  table th, table td { border: 1px solid #d5d6dd; padding: 6px 10px; text-align: left; }
  table th { background: #f1f1f4; }
  a { color: #3759d8; }
  .hint { font-size: 0.85em; color: #777; margin-top: 2em; padding-top: 1em; border-top: 1px solid #d5d6dd; }
</style>
</head>
<body>
${body}
<p class="hint">This page was generated by the BMC Helix AIOps install bundle. Configurator UI: <a href="http://localhost:8765">http://localhost:8765</a></p>
</body>
</html>
`;
};

// Slim Dockerfile shipped in the install zip. The repo's main Dockerfile
// has a frontend-build stage that depends on the frontend/ source — but
// inside the running configurator container we only have the *built*
// frontend-dist. So the install bundle uses a single-stage Dockerfile that
// installs backend prod deps and copies the prebuilt frontend straight in.
// In-bundle update script. Ships inside helix-configurator/ and refreshes the
// install in place — same preserve-user-files semantics as the installer's
// existing update path, but without needing to revisit the AIOps page for a
// new token. The self-relocate at the top is load-bearing: the script is
// about to delete its own directory, so we copy it to /tmp and exec from
// there before doing any destructive work.
const renderUpdateBash = ({ installBaseUrl, interactive }) => `#!/usr/bin/env bash
set -e
INSTALL_BASE_URL='${installBaseUrl}'

# Self-relocate to /tmp so we can recreate helix-configurator/ wholesale
# without ripping out the script file we're executing from.
if [ -z "$HELIX_UPDATE_RELOCATED" ]; then
  RELOC=$(mktemp "\${TMPDIR:-/tmp}/helix-update.XXXXXX.sh")
  cp "$0" "$RELOC"
  chmod +x "$RELOC"
  PARENT_DIR=$(cd "$(dirname "$0")/.." && pwd)
  HELIX_UPDATE_RELOCATED=1 HELIX_UPDATE_PARENT="$PARENT_DIR" exec bash "$RELOC"
fi
${interactive ? "trap 'echo \"\"; read -p \"Press Return to close...\" _' EXIT\n" : ''}
echo "================================================"
echo " Helix OTel Configurator -- Update"
echo "================================================"
echo ""
echo "Source URL: $INSTALL_BASE_URL"
echo ""

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker isn't installed."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "Docker is installed but not running. Start Docker Desktop and re-run."
  exit 1
fi

cd "$HELIX_UPDATE_PARENT"

if [ ! -d helix-configurator ]; then
  echo "Error: no helix-configurator/ directory at $HELIX_UPDATE_PARENT."
  echo "Run update.sh from inside the helix-configurator/ directory."
  exit 1
fi

echo "Stopping current sidecar..."
( cd helix-configurator && docker compose down 2>/dev/null || true )

echo "Preserving .env, helix-otel-collector.yaml, and data/..."
HELIX_BAK=$(mktemp -d "\${TMPDIR:-/tmp}/helix-update.XXXXXX")
for keep in .env helix-otel-collector.yaml data; do
  if [ -e "helix-configurator/$keep" ]; then
    cp -R "helix-configurator/$keep" "$HELIX_BAK/"
  fi
done

echo "Downloading latest bundle from $INSTALL_BASE_URL ..."
if ! curl -fsSL "$INSTALL_BASE_URL/api/_demo/aiops/latest.zip" -o package.zip; then
  echo ""
  echo "Failed to download from $INSTALL_BASE_URL."
  echo "If the install host's tunnel URL has changed, re-run the original"
  echo "install one-liner from the AIOps page instead."
  rm -rf "$HELIX_BAK"
  exit 1
fi

rm -rf helix-configurator
echo "Extracting..."
unzip -oq package.zip
rm package.zip
if [ ! -d helix-configurator ]; then
  echo "Error: extraction failed — helix-configurator/ directory missing."
  echo "Restoring preserved files..."
  mkdir -p helix-configurator
  cp -R "$HELIX_BAK/." helix-configurator/ 2>/dev/null || true
  rm -rf "$HELIX_BAK"
  exit 1
fi

# Re-overlay user files on top of the fresh extract.
for keep in .env helix-otel-collector.yaml data; do
  if [ -e "$HELIX_BAK/$keep" ]; then
    rm -rf "helix-configurator/$keep"
    cp -R "$HELIX_BAK/$keep" "helix-configurator/"
  fi
done
rm -rf "$HELIX_BAK"

cd helix-configurator
echo "Rebuilding image and starting..."
docker compose up -d --build

echo "Waiting for the configurator to come back online..."
deadline=$(( $(date +%s) + 60 ))
while [ $(date +%s) -lt $deadline ]; do
  if curl -fsS http://localhost:8765/api/health >/dev/null 2>&1; then
    echo "Update complete."
    break
  fi
  sleep 1
done
`;

const renderUpdateBat = ({ installBaseUrl }) => `@echo off
setlocal enabledelayedexpansion
set "INSTALL_BASE_URL=${installBaseUrl}"

REM Self-relocate so we can safely tear down and re-create helix-configurator/.
if not defined HELIX_UPDATE_RELOCATED (
  set "RELOC=%TEMP%\\helix-update-%RANDOM%.bat"
  copy "%~f0" "!RELOC!" >nul
  set "HELIX_UPDATE_RELOCATED=1"
  set "HELIX_UPDATE_PARENT=%~dp0.."
  cmd /c "!RELOC!"
  exit /b !ERRORLEVEL!
)

echo ================================================
echo  Helix OTel Configurator -- Update
echo ================================================
echo.
echo Source URL: %INSTALL_BASE_URL%
echo.

where docker >nul 2>&1
if errorlevel 1 (
  echo Docker isn't installed.
  pause
  exit /b 1
)
docker info >nul 2>&1
if errorlevel 1 (
  echo Docker is installed but not running. Start Docker Desktop and re-run.
  pause
  exit /b 1
)

cd /d "%HELIX_UPDATE_PARENT%"

if not exist "helix-configurator" (
  echo Error: no helix-configurator\\ directory at %HELIX_UPDATE_PARENT%.
  echo Run update.bat from inside the helix-configurator\\ directory.
  pause
  exit /b 1
)

echo Stopping current sidecar...
pushd helix-configurator >nul
docker compose down >nul 2>&1
popd >nul

echo Preserving .env, helix-otel-collector.yaml, and data\\ ...
set "HELIX_BAK=%TEMP%\\helix-update-%RANDOM%"
mkdir "%HELIX_BAK%" >nul
if exist "helix-configurator\\.env" copy "helix-configurator\\.env" "%HELIX_BAK%\\.env" >nul
if exist "helix-configurator\\helix-otel-collector.yaml" copy "helix-configurator\\helix-otel-collector.yaml" "%HELIX_BAK%\\helix-otel-collector.yaml" >nul
if exist "helix-configurator\\data" xcopy "helix-configurator\\data" "%HELIX_BAK%\\data\\" /E /I /Q /Y >nul

echo Downloading latest bundle...
powershell -NoProfile -Command "try { Invoke-WebRequest -UseBasicParsing -Uri '%INSTALL_BASE_URL%/api/_demo/aiops/latest.zip' -OutFile 'package.zip' } catch { exit 1 }"
if errorlevel 1 (
  echo.
  echo Failed to download from %INSTALL_BASE_URL%.
  echo If the install host's tunnel URL has changed, re-run the original
  echo install one-liner from the AIOps page instead.
  rd /s /q "%HELIX_BAK%"
  pause
  exit /b 1
)

rd /s /q helix-configurator
powershell -NoProfile -Command "Expand-Archive -Force -Path 'package.zip' -DestinationPath '.'"
del package.zip
if not exist "helix-configurator" (
  echo Extraction failed.
  rd /s /q "%HELIX_BAK%"
  pause
  exit /b 1
)

if exist "%HELIX_BAK%\\.env" copy /Y "%HELIX_BAK%\\.env" "helix-configurator\\.env" >nul
if exist "%HELIX_BAK%\\helix-otel-collector.yaml" copy /Y "%HELIX_BAK%\\helix-otel-collector.yaml" "helix-configurator\\helix-otel-collector.yaml" >nul
if exist "%HELIX_BAK%\\data" xcopy "%HELIX_BAK%\\data" "helix-configurator\\data\\" /E /I /Q /Y >nul
rd /s /q "%HELIX_BAK%"

cd helix-configurator
echo Rebuilding image and starting...
docker compose up -d --build
if errorlevel 1 (
  echo.
  echo Build failed. See errors above.
  pause
  exit /b 1
)

echo Waiting for the configurator to come back online...
set /a "_waited=0"
:waitloop
powershell -NoProfile -Command "try { Invoke-WebRequest -UseBasicParsing -Uri 'http://localhost:8765/api/health' -TimeoutSec 2 | Out-Null; exit 0 } catch { exit 1 }" >nul 2>&1
if not errorlevel 1 (
  echo Update complete.
  goto :done
)
set /a "_waited+=1"
if %_waited% geq 60 goto :done
timeout /t 1 /nobreak >nul
goto :waitloop
:done
echo.
pause
`;

const renderInstallDockerfile = () => `FROM node:20-slim
WORKDIR /app

# Install backend production dependencies. Pin via package-lock.json.
COPY backend/package*.json ./backend/
RUN cd backend && npm install --omit=dev

# App source. frontend-dist is the already-built Vite bundle.
COPY backend/ ./backend/
COPY templates/ ./templates/
COPY frontend-dist/ ./frontend-dist/

EXPOSE 3001
CMD ["node", "backend/index.js"]
`;

const writePackageToArchive = (archive, ctx, projectRoot) => {
  if (!ctx.installBaseUrl) {
    throw new Error('writePackageToArchive: ctx.installBaseUrl is required (set via computeInstallBaseUrl(req))');
  }
  archive.append(renderDockerCompose(), { name: 'helix-configurator/docker-compose.yml' });
  archive.append(renderCollectorYaml(ctx), { name: 'helix-configurator/helix-otel-collector.yaml' });
  archive.append(renderEnvFile(ctx), { name: 'helix-configurator/.env' });
  archive.append(renderShellLauncher({ interactive: false }), { name: 'helix-configurator/start.sh', mode: 0o755 });
  archive.append(renderShellLauncher({ interactive: true }), { name: 'helix-configurator/start.command', mode: 0o755 });
  archive.append(renderStartBat(), { name: 'helix-configurator/start.bat' });
  archive.append(renderUpdateBash({ installBaseUrl: ctx.installBaseUrl, interactive: false }), { name: 'helix-configurator/update.sh', mode: 0o755 });
  archive.append(renderUpdateBash({ installBaseUrl: ctx.installBaseUrl, interactive: true }), { name: 'helix-configurator/update.command', mode: 0o755 });
  archive.append(renderUpdateBat({ installBaseUrl: ctx.installBaseUrl }), { name: 'helix-configurator/update.bat' });
  archive.append(renderReadme(ctx), { name: 'helix-configurator/README.md' });
  archive.append(renderReadmeHtml(ctx), { name: 'helix-configurator/README.html' });
  archive.append(renderInstallDockerfile(), { name: 'helix-configurator/Dockerfile' });

  // projectRoot is /app at runtime (the configurator container's WORKDIR).
  // /app contains only the runtime artifacts: backend/, templates/,
  // frontend-dist/. There is no Dockerfile or frontend/ source here — the
  // install Dockerfile above is generated inline, and we glob frontend-dist
  // (the built bundle).
  const ignore = ['**/node_modules/**', '**/.DS_Store', '**/dist/**', '**/.git/**'];
  archive.glob('backend/**/*', { cwd: projectRoot, ignore, dot: true }, { prefix: 'helix-configurator' });
  archive.glob('frontend-dist/**/*', { cwd: projectRoot, ignore, dot: true }, { prefix: 'helix-configurator' });
  archive.glob('templates/**/*', { cwd: projectRoot, ignore, dot: true }, { prefix: 'helix-configurator' });
};

const renderBashInstaller = ({ token, baseUrl, xSource }) => {
  // Single-quoted bash literals — escape only the values we interpolate.
  const safeName = xSource.replace(/[^A-Za-z0-9._-]+/g, '-');
  return `#!/usr/bin/env bash
set -e
TOKEN='${token}'
BASE_URL='${baseUrl}'
XSOURCE='${safeName}'
# Install into the directory the user ran the install command from. \`pwd\`
# inside a curl|bash pipe reflects the parent shell's cwd, which is what
# users expect (run from ~/projects → install lands in ~/projects/...).
TARGET="$(pwd)/helix-configurator-\${XSOURCE}"

echo "================================================"
echo " Helix OTel Configurator — One-line install"
echo "================================================"
echo ""
echo "Source:  $XSOURCE"
echo "Target:  $TARGET"
echo ""

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker isn't installed. Install Docker Desktop and re-run:"
  echo "  https://www.docker.com/products/docker-desktop/"
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  if [ "$(uname)" = "Darwin" ] && [ -d "/Applications/Docker.app" ]; then
    echo "Docker is installed but not running. Starting Docker Desktop..."
    open -a Docker
    printf "Waiting for the Docker daemon to become ready (up to 2 minutes)"
    deadline=$(( $(date +%s) + 120 ))
    while [ $(date +%s) -lt $deadline ]; do
      sleep 3
      if docker info >/dev/null 2>&1; then printf " ready\\n"; break; fi
      printf "."
    done
    if ! docker info >/dev/null 2>&1; then
      printf "\\n"
      echo "Docker Desktop didn't finish starting in 2 minutes."
      echo "Wait for the whale icon in the menu bar to settle, then re-run this command."
      exit 1
    fi
  else
    echo "Docker is installed but not running. Start the Docker daemon, then re-run this command."
    exit 1
  fi
fi

mkdir -p "$TARGET"
cd "$TARGET"

# If a prior install exists, back up user-owned files so we can refresh the
# source code without nuking real credentials, edited gateway YAML, or the
# local OTel trace store.
HELIX_BAK=""
if [ -d helix-configurator ]; then
  echo "Existing install detected — preserving .env, helix-otel-collector.yaml, and data/."
  HELIX_BAK=$(mktemp -d "\${TMPDIR:-/tmp}/helix-update.XXXXXX")
  for keep in .env helix-otel-collector.yaml data; do
    if [ -e "helix-configurator/$keep" ]; then
      cp -R "helix-configurator/$keep" "$HELIX_BAK/"
    fi
  done
fi

# Force a clean slate so a partial/stale extract from a prior failed run can't
# leave a corrupt Dockerfile (etc.) that survives unzip -o.
rm -rf helix-configurator
echo "Downloading package..."
curl -fsSL "$BASE_URL/api/_demo/aiops/package/$TOKEN" -o package.zip
echo "Extracting..."
unzip -oq package.zip
rm package.zip
if [ ! -d helix-configurator ]; then
  echo "Error: extraction failed — helix-configurator/ directory missing."
  if [ -n "$HELIX_BAK" ]; then
    echo "Restoring preserved files..."
    mkdir -p helix-configurator
    cp -R "$HELIX_BAK/." helix-configurator/ 2>/dev/null || true
    rm -rf "$HELIX_BAK"
  fi
  exit 1
fi

# Re-overlay user files on top of the fresh extract. The bundle ships
# placeholder versions of .env / helix-otel-collector.yaml; those are useful
# on a first install but would clobber real values on update.
if [ -n "$HELIX_BAK" ]; then
  for keep in .env helix-otel-collector.yaml data; do
    if [ -e "$HELIX_BAK/$keep" ]; then
      rm -rf "helix-configurator/$keep"
      cp -R "$HELIX_BAK/$keep" "helix-configurator/"
    fi
  done
  rm -rf "$HELIX_BAK"
fi
cd helix-configurator
for required in Dockerfile docker-compose.yml .env; do
  if [ ! -f "$required" ]; then
    echo "Error: '$required' is missing after extract. Listing:"
    ls -la
    exit 1
  fi
done
echo "Building image and starting (first run takes a few minutes)..."
docker compose up -d --build
echo ""
echo "Waiting for the configurator UI to come online..."
deadline=$(( $(date +%s) + 60 ))
while [ $(date +%s) -lt $deadline ]; do
  if curl -fsS http://localhost:8765/api/health >/dev/null 2>&1; then
    echo "Opening README and configurator UI..."
    if [ "$(uname)" = "Darwin" ]; then
      [ -f README.html ] && open README.html || true
      open "http://localhost:8765?view=onboarding" || true
    elif [ -n "$DISPLAY" ] && command -v xdg-open >/dev/null 2>&1; then
      [ -f README.html ] && (xdg-open README.html >/dev/null 2>&1 &)
      (xdg-open "http://localhost:8765?view=onboarding" >/dev/null 2>&1 &)
    fi
    break
  fi
  sleep 1
done
echo ""
echo "Sidecar is up."
echo "  Configurator UI:  http://localhost:8765"
echo "  OTLP gRPC:        localhost:4317"
echo "  OTLP HTTP:        localhost:4318"
echo ""
echo "Installed to: $TARGET/helix-configurator"
echo "Stop with:    cd $TARGET/helix-configurator && docker compose down"
`;
};

const renderPowerShellInstaller = ({ token, baseUrl, xSource }) => {
  const safeName = xSource.replace(/[^A-Za-z0-9._-]+/g, '-');
  return `$ErrorActionPreference = 'Stop'
$Token = '${token}'
$BaseUrl = '${baseUrl}'
$XSource = '${safeName}'
# Install into the directory PowerShell was run from. \$PWD reflects the
# caller's location even when invoked via 'iwr | iex', so running from
# C:\\Users\\james\\source\\repos drops the install there, not in \$HOME.
$Target = Join-Path $PWD.Path "helix-configurator-$XSource"

# PowerShell treats stderr from native commands as a terminating error when
# $ErrorActionPreference is 'Stop' (PS 7.3+ via $PSNativeCommandUseErrorActionPreference).
# Wrap docker calls so we can check $LASTEXITCODE explicitly without the
# script aborting on stderr that docker / BuildKit emits during normal use.
function Test-DockerRunning {
  $ErrorActionPreference = 'SilentlyContinue'
  docker info 2>&1 | Out-Null
  return ($LASTEXITCODE -eq 0)
}

Write-Host "================================================"
Write-Host " Helix OTel Configurator -- One-line install"
Write-Host "================================================"
Write-Host ""
Write-Host "Source:  $XSource"
Write-Host "Target:  $Target"
Write-Host ""

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Write-Host "Docker isn't installed. Install Docker Desktop and re-run:"
  Write-Host "  https://www.docker.com/products/docker-desktop/"
  exit 1
}
if (-not (Test-DockerRunning)) {
  $dockerExe = "$env:ProgramFiles\\Docker\\Docker\\Docker Desktop.exe"
  if (-not (Test-Path $dockerExe)) {
    $dockerExe = "$env:LOCALAPPDATA\\Docker\\Docker Desktop.exe"
  }
  if (Test-Path $dockerExe) {
    Write-Host "Docker is installed but not running. Starting Docker Desktop..."
    Start-Process -FilePath $dockerExe
    Write-Host -NoNewline "Waiting for the Docker daemon to become ready (up to 2 minutes)"
    $deadline = (Get-Date).AddMinutes(2)
    $ready = $false
    while ((Get-Date) -lt $deadline) {
      Start-Sleep -Seconds 3
      if (Test-DockerRunning) { $ready = $true; break }
      Write-Host -NoNewline "."
    }
    if ($ready) {
      Write-Host " ready"
    } else {
      Write-Host ""
      Write-Host "Docker Desktop didn't finish starting in 2 minutes."
      Write-Host "Wait for the whale icon in the system tray to stop animating, then re-run this command."
      exit 1
    }
  } else {
    Write-Host "Docker Desktop binary not found at the default install path. Open Docker Desktop manually, wait for the whale icon to settle, then re-run this command."
    exit 1
  }
}

New-Item -ItemType Directory -Force -Path $Target | Out-Null
Set-Location $Target

# If a prior install exists, back up user-owned files so re-running the
# installer refreshes the source code without nuking real credentials, edited
# gateway YAML, or the local OTel trace store.
$bak = $null
if (Test-Path "helix-configurator") {
  Write-Host "Existing install detected -- preserving .env, helix-otel-collector.yaml, and data/."
  $bak = Join-Path $env:TEMP ("helix-update-" + [System.IO.Path]::GetRandomFileName())
  New-Item -ItemType Directory -Force -Path $bak | Out-Null
  foreach ($keep in @('.env', 'helix-otel-collector.yaml', 'data')) {
    $src = Join-Path "helix-configurator" $keep
    if (Test-Path $src) { Copy-Item -Recurse -Force $src $bak }
  }
}

# Force a clean slate so a partial/stale extract can't leave a corrupt file behind.
if (Test-Path "helix-configurator") { Remove-Item -Recurse -Force "helix-configurator" }
Write-Host "Downloading package..."
Invoke-WebRequest -UseBasicParsing -Uri "$BaseUrl/api/_demo/aiops/package/$Token" -OutFile "package.zip"
Write-Host "Extracting..."
Expand-Archive -Force -Path "package.zip" -DestinationPath "."
Remove-Item "package.zip"
if (-not (Test-Path "helix-configurator")) {
  Write-Host "Error: extraction failed -- helix-configurator/ directory missing."
  if ($bak) {
    Write-Host "Restoring preserved files..."
    New-Item -ItemType Directory -Force -Path "helix-configurator" | Out-Null
    Get-ChildItem -Force -Path $bak | ForEach-Object {
      Copy-Item -Recurse -Force $_.FullName "helix-configurator"
    }
    Remove-Item -Recurse -Force $bak
  }
  exit 1
}

# Re-overlay user files on top of the fresh extract. The bundle ships
# placeholder versions of .env / helix-otel-collector.yaml; those are useful
# on a first install but would clobber real values on update.
if ($bak) {
  foreach ($keep in @('.env', 'helix-otel-collector.yaml', 'data')) {
    $src = Join-Path $bak $keep
    if (Test-Path $src) {
      $dst = Join-Path "helix-configurator" $keep
      if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
      Copy-Item -Recurse -Force $src "helix-configurator"
    }
  }
  Remove-Item -Recurse -Force $bak
}

Set-Location "helix-configurator"
foreach ($required in @('Dockerfile', 'docker-compose.yml', '.env')) {
  if (-not (Test-Path $required)) {
    Write-Host "Error: '$required' is missing after extract. Listing:"
    Get-ChildItem -Force | Format-Table
    exit 1
  }
}
Write-Host "Building image and starting (first run takes a few minutes)..."
# BuildKit emits build progress to stderr, which would terminate the script
# under $ErrorActionPreference = 'Stop'. Relax it just for the build call so
# the user sees full progress and we can act on the real exit code.
$prevPref = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
docker compose up -d --build
$buildExit = $LASTEXITCODE
$ErrorActionPreference = $prevPref
if ($buildExit -ne 0) {
  Write-Host ""
  Write-Host "Failed to start the sidecar. See errors above."
  exit 1
}

Write-Host ""
Write-Host "Waiting for the configurator UI to come online..."
$deadline = (Get-Date).AddSeconds(60)
while ((Get-Date) -lt $deadline) {
  try {
    Invoke-WebRequest -UseBasicParsing -Uri "http://localhost:8765/api/health" -TimeoutSec 2 | Out-Null
    Write-Host "Opening http://localhost:8765 ..."
    Start-Process "http://localhost:8765?view=onboarding"
    break
  } catch {
    Start-Sleep -Seconds 1
  }
}

Write-Host ""
Write-Host "Sidecar is up."
Write-Host "  Configurator UI:  http://localhost:8765"
Write-Host "  OTLP gRPC:        localhost:4317"
Write-Host "  OTLP HTTP:        localhost:4318"
Write-Host ""
Write-Host "Installed to: $Target\\helix-configurator"
Write-Host "Stop with:    cd $Target\\helix-configurator; docker compose down"
`;
};

function register(app, { projectRoot }) {
  // POST /api/_demo/aiops/configure — create a session, return token + simulated key.
  app.post('/api/_demo/aiops/configure', (req, res) => {
    const { xSource } = req.body || {};
    if (typeof xSource !== 'string' || !xSource.trim()) {
      return res.status(400).json({ error: 'xSource is required' });
    }
    const session = {
      xSource: xSource.trim(),
      endpoint: SIMULATED_INGEST_ENDPOINT,
      apiKey: fakeHelixApiKey(),
      createdAt: Date.now(),
    };
    const token = crypto.randomBytes(16).toString('hex');
    aiopsSessions.set(token, session);
    res.json({
      token,
      apiKey: session.apiKey,
      xSource: session.xSource,
      endpoint: session.endpoint,
      // The host portion of installBaseUrl will be the LAN IP when the request
      // came from localhost — so the curl/iwr command shown in the UI works
      // when pasted on a different machine on the same network.
      installBaseUrl: computeInstallBaseUrl(req),
    });
  });

  // GET /api/_demo/aiops/package/:token — stream the configured zip.
  app.get('/api/_demo/aiops/package/:token', (req, res) => {
    const session = aiopsSessions.get(req.params.token);
    if (!session) return res.status(404).json({ error: 'Session expired or not found' });
    const safeName = session.xSource.replace(/[^A-Za-z0-9._-]+/g, '-');
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="helix-configurator-${safeName}.zip"`);
    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('error', (err) => {
      console.error('archive error:', err);
      if (!res.headersSent) res.status(500).end();
      else res.end();
    });
    archive.pipe(res);
    // Compute installBaseUrl per-request — if the user downloads through a
    // different tunnel URL than the one captured at configure time, the
    // baked-in update.* scripts should reflect the URL the bundle was
    // actually fetched from.
    writePackageToArchive(archive, { ...session, installBaseUrl: computeInstallBaseUrl(req) }, projectRoot);
    archive.finalize();
  });

  // GET /api/_demo/aiops/latest.zip — token-less bundle for in-place updates
  // (called by update.sh / update.command / update.bat). The .env is a stub
  // since the update script preserves the caller's existing .env. Gated by
  // the same IS_DEMO_INSTALL flag that registers this whole module.
  app.get('/api/_demo/aiops/latest.zip', (req, res) => {
    const stubCtx = {
      xSource: 'helix-otel',
      endpoint: SIMULATED_INGEST_ENDPOINT,
      apiKey: fakeHelixApiKey(),
      installBaseUrl: computeInstallBaseUrl(req),
    };
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename="helix-configurator-latest.zip"');
    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('error', (err) => {
      console.error('archive error:', err);
      if (!res.headersSent) res.status(500).end();
      else res.end();
    });
    archive.pipe(res);
    writePackageToArchive(archive, stubCtx, projectRoot);
    archive.finalize();
  });

  // GET /api/_demo/aiops/install/:token.sh — bash one-liner installer.
  app.get('/api/_demo/aiops/install/:token.sh', (req, res) => {
    const session = aiopsSessions.get(req.params.token);
    if (!session) {
      return res.status(404).type('text/plain').send('# Session expired or not found\nexit 1\n');
    }
    const baseUrl = computeInstallBaseUrl(req);
    res.type('text/x-shellscript');
    res.send(renderBashInstaller({ token: req.params.token, baseUrl, xSource: session.xSource }));
  });

  // GET /api/_demo/aiops/install/:token.ps1 — PowerShell one-liner installer.
  app.get('/api/_demo/aiops/install/:token.ps1', (req, res) => {
    const session = aiopsSessions.get(req.params.token);
    if (!session) {
      return res.status(404).type('text/plain').send('# Session expired or not found\nexit 1\n');
    }
    const baseUrl = computeInstallBaseUrl(req);
    res.type('text/plain');
    res.send(renderPowerShellInstaller({ token: req.params.token, baseUrl, xSource: session.xSource }));
  });
}

module.exports = { register };
